package messaging;

public enum Command {

    LOGIN,
    LOGOUT,
    CREATE_ACCOUNT,
    GET_ROOMS,
    JOIN_ROOM,
    SEND_CHAT_MESSAGE,
    RECEIVE_CHAT_MESSAGE,
    USERS_IN_ROOM,
    REQUEST_USERS,
    EXIT_ROOM,
    CONFIRM_EXIT,
    START_DRAWING,
    DRAW_PATH,
    INCOMING_PATH,
    STOP_DRAWING,
    CLEAR_CANVAS,
    GET_SCORES,
    CONFIRM_JOIN_ROOM,
    REJECT_JOIN_ROOM

}
