package messaging;

public enum Command {

    LOGIN,
    LOGOUT,
    CREATE_ROOM,
    GET_ROOMS,
    JOIN_ROOM,
    SEND_CHAT_MESSAGE,
    RECEIVE_CHAT_MESSAGE,
    ROOM_LIST,
    TEST,
    CONFIRM_ROOM_JOIN,
    USERS_IN_ROOM,
    REQUEST_USERS,
    EXIT_ROOM,
    CONFIRM_EXIT,
    START_DRAWING,
    DRAW_PATH,
    INCOMING_PATH,
    STOP_DRAWING

}
